name: NestJS Build and Notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-workflow-build-push:
    uses: petpusin/github-reuse-workflows/.github/workflows/build-push.yaml@main
  call-workflow-bearer:
    uses: ./bearer.yaml
  # call-workflow-discord-noti:
  #   needs: [call-workflow-build-push]
  #   secrets:
  #     WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
  #   with:
  #     message: "test"

  #   uses: petpusin/github-reuse-workflows/.github/workflows/discord-noti.yaml@main
