name: NestJS Build and Notification

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-workflow-build-push:
    uses: petpusin/github-reuse-workflows/build-push.yaml@main

  call-workflow-discord-noti:
    needs: [call-workflow-build-push]
    uses: petpusin/github-reuse-workflows/discord-noti.yaml@main
